### ISSUE TITLE
`yarn bootstrap` fails due to missing DATABASE_URL env var

### ISSUE THREAD

**Issue by wtodom** [O4epegb/dcss-stats#19]
First, thanks for making and maintaining the app! I've used it for a while now and love it.

I'm trying to get setup to potentially work on some of the starter tasks you've already defined here as well as the original thing I came here for - to try to update the Skill Progression visualization to not truncate skill names. I believe I found the source of the truncation and also have a potential fix, but I'm stuck unable to actually get the full stack to bootstrap and run without errors. Specifically, this is what I'm seeing when I run `yarn bootstrap`:

```➜  dcss-stats git:(master) yarn bootstrap
➤ YN0000: · Yarn 4.5.1
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ eslint is listed by your project with version 9.7.0 (p02bd9), which doesn't satisfy what eslint-plugin-import and other dependencies request (^8.56.0).
➤ YN0060: │ eslint is listed by your project with version 9.7.0 (p54a88), which doesn't satisfy what eslint-plugin-import and other dependencies request (^8.56.0).
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings in 0s 390ms
╭──────────────────────────────────────────────────────────────────────────╮
│                                                                          │
│                     Update available v2.2.3 ≫ v2.3.3                     │
│    Changelog: https://github.com/vercel/turborepo/releases/tag/v2.3.3    │
│             Run "npx @turbo/codemod@latest update" to update             │
│                                                                          │
│          Follow @turborepo for updates: https://x.com/turborepo          │
╰──────────────────────────────────────────────────────────────────────────╯
turbo 2.2.3

• Packages in scope: @dcss-stats/api, @dcss-stats/web
• Running bootstrap in 2 packages
• Remote caching disabled
@dcss-stats/api:bootstrap: cache bypass, force executing 9b39c2f54e3f30f1
@dcss-stats/api:bootstrap:
[+] Running 1/0:bootstrap:
@dcss-stats/api:bootstrap:  ✔ Network dcss-api_default  Created                                                                 [+] Running 1/2       0.0s
@dcss-stats/api:bootstrap:  ✔ Network dcss-api_default  Created                                                                 [+] Running 2/2       0.0s
@dcss-stats/api:bootstrap:  ✔ Network dcss-api_default  Created                                                                                       0.0s
@dcss-stats/api:bootstrap:  ✔ Container postgres16      Started                                                                                       0.2s
@dcss-stats/api:bootstrap: Prisma schema loaded from prisma/schema.prisma
@dcss-stats/api:bootstrap:
@dcss-stats/api:bootstrap: ✔ Generated Prisma Client (v5.20.0) to ./../../node_modules/@prisma/client in 66ms
@dcss-stats/api:bootstrap:
@dcss-stats/api:bootstrap: Start by importing your Prisma Client (See: http://pris.ly/d/importing-client)
@dcss-stats/api:bootstrap:
@dcss-stats/api:bootstrap: Tip: Interested in query caching in just a few lines of code? Try Accelerate today! https://pris.ly/tip-3-accelerate
@dcss-stats/api:bootstrap:
@dcss-stats/api:bootstrap: Prisma schema loaded from prisma/schema.prisma
@dcss-stats/api:bootstrap: Datasource "db": PostgreSQL database
@dcss-stats/api:bootstrap:
@dcss-stats/api:bootstrap: Error: Prisma schema validation - (get-config wasm)
@dcss-stats/api:bootstrap: Error code: P1012
@dcss-stats/api:bootstrap: error: Environment variable not found: DATABASE_URL.
@dcss-stats/api:bootstrap:   -->  prisma/schema.prisma:3
@dcss-stats/api:bootstrap:    |
@dcss-stats/api:bootstrap:  2 |   provider = "postgresql"
@dcss-stats/api:bootstrap:  3 |   url      = env("DATABASE_URL")
@dcss-stats/api:bootstrap:    |
@dcss-stats/api:bootstrap:
@dcss-stats/api:bootstrap: Validation Error Count: 1
@dcss-stats/api:bootstrap: [Context: getConfig]
@dcss-stats/api:bootstrap:
@dcss-stats/api:bootstrap: Prisma CLI Version : 5.20.0
@dcss-stats/api:bootstrap: Running seed command `tsx prisma/seed.ts` ...
@dcss-stats/api:bootstrap: PrismaClientInitializationError:
@dcss-stats/api:bootstrap: Invalid `prisma.server.upsert()` invocation in
@dcss-stats/api:bootstrap: /Users/westonodom/repos/dcss-stats/apps/api/prisma/seed.ts:16:35
@dcss-stats/api:bootstrap:
@dcss-stats/api:bootstrap:   13   morgueUrl: server.morgueUrl,
@dcss-stats/api:bootstrap:   14   isDormant: 'isDormant' in server ? server.isDormant : false,
@dcss-stats/api:bootstrap:   15 }
@dcss-stats/api:bootstrap: → 16 const s = await prisma.server.upsert(
@dcss-stats/api:bootstrap: error: Environment variable not found: DATABASE_URL.
@dcss-stats/api:bootstrap:   -->  schema.prisma:3
@dcss-stats/api:bootstrap:    |
@dcss-stats/api:bootstrap:  2 |   provider = "postgresql"
@dcss-stats/api:bootstrap:  3 |   url      = env("DATABASE_URL")
@dcss-stats/api:bootstrap:    |
@dcss-stats/api:bootstrap:
@dcss-stats/api:bootstrap: Validation Error Count: 1
@dcss-stats/api:bootstrap:     at Mn.handleRequestError (/Users/westonodom/repos/dcss-stats/node_modules/@prisma/client/runtime/library.js:121:8053)
@dcss-stats/api:bootstrap:     at Mn.handleAndLogRequestError (/Users/westonodom/repos/dcss-stats/node_modules/@prisma/client/runtime/library.js:121:7061)
@dcss-stats/api:bootstrap:     at Mn.request (/Users/westonodom/repos/dcss-stats/node_modules/@prisma/client/runtime/library.js:121:6745)
@dcss-stats/api:bootstrap:     at async l (/Users/westonodom/repos/dcss-stats/node_modules/@prisma/client/runtime/library.js:130:9633)
@dcss-stats/api:bootstrap:     at main (/Users/westonodom/repos/dcss-stats/apps/api/prisma/seed.ts:16:15) {
@dcss-stats/api:bootstrap:   clientVersion: '5.20.0',
@dcss-stats/api:bootstrap:   errorCode: undefined
@dcss-stats/api:bootstrap: }
@dcss-stats/api:bootstrap:
@dcss-stats/api:bootstrap: An error occurred while running the seed command:
@dcss-stats/api:bootstrap: Error: Command failed with exit code 1: tsx prisma/seed.ts

 Tasks:    1 successful, 1 total
Cached:    0 cached, 1 total
  Time:    4.518s
```

It does appear that docker is successfully running postgres in the image that `yarn bootstrap` created, but based on the error message I'm assuming that that's not even relevant yet. I can successfully run just the frontend using `yarn dev --filter=@dcss-stats/web` with the backend set to prod like the readme describes, but everything I've tried to get the backend to startup locally has failed similarly to the above error. 

The instructions in the readme are pretty simple so it seems like either they're slightly out of date, or (probably more likely) I've got an env issue locally on my end. Do I need to have setup a db for that to use and add the connection string to `.env.development`? If not, are you able to help me figure out what's causing the issue? I'll be watching this thread and will try to get any additional info you need asap. Thanks!

**Comment by wtodom** [comment]
Oh, and just in case it's not clear - even though it says that 1 of 1 were successful, the site 500s. I can provide the web errors if that'll help, just let me know!

**Comment by O4epegb** [comment]
@wtodom  Hey, sorry, just saw the issue!

Hm.. I have not tried to debug it yet, but maybe you just need to make an `.env.local` file in `api` folder with `DATABASE_URL='postgresql://postgres:postgres@localhost:5432/dcssstats'`

I think I probably should add an `.env.development` file with this as default, otherwise `bootstrap` is pointless it seems 😅 

Let me know if it solves the issue!

**Comment by O4epegb** [comment]
> Oh, and just in case it's not clear - even though it says that 1 of 1 were successful, the site 500s. I can provide the web errors if that'll help, just let me know!

Weird that it says that it was successful, maybe it's a `turbo` bug or something in our setup is wrong, will try to figure out too later!

**Comment by O4epegb** [comment]
Added `.env.development` https://github.com/O4epegb/dcss-stats/commit/ab8993a9b871b3ee96e48269165d8d5e9e59f289
